server:
  port: 9020
  
eureka:
  instance:
    hostname: localhost
    
spring:
  application:
    name: form-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
              allowedOrigins: "http://localhost:4200"
              allowedMethods:
              - POST
              - GET
              - OPTIONS
              allowedHeaders: "*"
              allowCredentials: true        
    
      routes:
        - id: form-service
          uri: lb://form-service
          predicates:
            - Path=/api/v1/form/**    
      